// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: fibonacci/fibonacci/fibonacci.proto

package fibonacci

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FibonacciClient is the client API for Fibonacci service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FibonacciClient interface {
	Number(ctx context.Context, in *FibRequest, opts ...grpc.CallOption) (*FibResponse, error)
	Sequence(ctx context.Context, in *FibRequest, opts ...grpc.CallOption) (Fibonacci_SequenceClient, error)
}

type fibonacciClient struct {
	cc grpc.ClientConnInterface
}

func NewFibonacciClient(cc grpc.ClientConnInterface) FibonacciClient {
	return &fibonacciClient{cc}
}

func (c *fibonacciClient) Number(ctx context.Context, in *FibRequest, opts ...grpc.CallOption) (*FibResponse, error) {
	out := new(FibResponse)
	err := c.cc.Invoke(ctx, "/fibonacci.Fibonacci/Number", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fibonacciClient) Sequence(ctx context.Context, in *FibRequest, opts ...grpc.CallOption) (Fibonacci_SequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Fibonacci_ServiceDesc.Streams[0], "/fibonacci.Fibonacci/Sequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &fibonacciSequenceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fibonacci_SequenceClient interface {
	Recv() (*FibResponse, error)
	grpc.ClientStream
}

type fibonacciSequenceClient struct {
	grpc.ClientStream
}

func (x *fibonacciSequenceClient) Recv() (*FibResponse, error) {
	m := new(FibResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FibonacciServer is the server API for Fibonacci service.
// All implementations must embed UnimplementedFibonacciServer
// for forward compatibility
type FibonacciServer interface {
	Number(context.Context, *FibRequest) (*FibResponse, error)
	Sequence(*FibRequest, Fibonacci_SequenceServer) error
	mustEmbedUnimplementedFibonacciServer()
}

// UnimplementedFibonacciServer must be embedded to have forward compatible implementations.
type UnimplementedFibonacciServer struct {
}

func (UnimplementedFibonacciServer) Number(context.Context, *FibRequest) (*FibResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Number not implemented")
}
func (UnimplementedFibonacciServer) Sequence(*FibRequest, Fibonacci_SequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method Sequence not implemented")
}
func (UnimplementedFibonacciServer) mustEmbedUnimplementedFibonacciServer() {}

// UnsafeFibonacciServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FibonacciServer will
// result in compilation errors.
type UnsafeFibonacciServer interface {
	mustEmbedUnimplementedFibonacciServer()
}

func RegisterFibonacciServer(s grpc.ServiceRegistrar, srv FibonacciServer) {
	s.RegisterService(&Fibonacci_ServiceDesc, srv)
}

func _Fibonacci_Number_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibonacciServer).Number(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fibonacci.Fibonacci/Number",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibonacciServer).Number(ctx, req.(*FibRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fibonacci_Sequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FibRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FibonacciServer).Sequence(m, &fibonacciSequenceServer{stream})
}

type Fibonacci_SequenceServer interface {
	Send(*FibResponse) error
	grpc.ServerStream
}

type fibonacciSequenceServer struct {
	grpc.ServerStream
}

func (x *fibonacciSequenceServer) Send(m *FibResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Fibonacci_ServiceDesc is the grpc.ServiceDesc for Fibonacci service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fibonacci_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fibonacci.Fibonacci",
	HandlerType: (*FibonacciServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Number",
			Handler:    _Fibonacci_Number_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sequence",
			Handler:       _Fibonacci_Sequence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fibonacci/fibonacci/fibonacci.proto",
}
